function createfigure(xdata1, ydata1, zdata1, X1, Y1, Z1)
%CREATEFIGURE(xdata1, ydata1, zdata1, X1, Y1, Z1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  X1:  vector of plot3 x data
%  Y1:  vector of plot3 y data
%  Z1:  vector of plot3 z data

%  Auto-generated by MATLAB on 04-Jan-2024 19:50:30

% Create figure
figure('WindowState','maximized','OuterPosition',[-6.2 33.8 1934.4 1054.4]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'FaceColor',[0.9 0.9 0.9],'EdgeColor','none');

% Create plot3
plot3(X1,Y1,Z1,'LineWidth',2,'Color',[0 0 0]);

% Create zlabel
zlabel('Z (mm)');

% Create ylabel
ylabel('Y (mm)');

% Create xlabel
xlabel('X (mm)');

% Create title
title('3D Visualisation');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.205269664065466 1.1629812530353]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1.14510255751518 -0.0659498180598939]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0.893837862272446 1.97299060172773]);
view(axes1,[45 30]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'FontSize',20,'PlotBoxAspectRatio',...
    [1.2678936605317 1 1],'XMinorGrid','on','YMinorGrid','on','ZMinorGrid','on');
